# Site
title: "Open Life Science"
description: >
  The Open Leader program for Open Life Science
logo: ''
email: 'berenice.batut@gmail.com'
repository: open-life-science/open-life-science.github.io
twitter: openlifesci

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/

includes_dir: .

plugins:
  - jekyll-last-modified-at