
name: open-life-science-website
channels:
  - conda-forge
  - defaults
dependencies:
  - gmp
  - jemalloc
  - nodejs
  - openssl
  - readline
  - ruby
  - yaml
  - yamllint
  - zlib
  - libxml2
  - pkg-config
  - pandas
  - pyyaml